-- Your SQL goes here
CREATE TABLE todos (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  is_done BOOLEAN NOT NULL DEFAULT FALSE,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT pkey_id PRIMARY KEY (id)
);
